### ISSUE TITLE
SMTP send seems to not work and no error is shown

### ISSUE THREAD

**Issue by philcarbone** [Quadrotech/ADOScheduledWorkItemQuery#3] opened 2019-05-18 02:02 UTC
I've setup the SMTP settings to match the SMTP settings in a mail client, but it doesn't seem to work with this extension. It isn't failing the build step either.

**Comment by MichelZ** [comment] 2019-05-21 15:32
Can you activate debug mode for the pipeline (set system.debug variable to true) and post the result of the task here? (Make sure to not include sensitive information)

**Comment by philcarbone** [comment] 2019-05-25 15:18
Here to go:
```
2019-05-25T15:13:21.1941572Z ##[section]Starting: Agent job 1
2019-05-25T15:13:21.2025599Z ##[debug]Cleaning agent temp folder: D:\a\_temp
2019-05-25T15:13:21.2069670Z ##[debug]Skipping overwrite %TEMP% environment variable
2019-05-25T15:13:21.4144121Z ##[section]Starting: Initialize job
2019-05-25T15:13:21.4144381Z Current agent version: '2.150.3'
2019-05-25T15:13:21.4237163Z ##[debug]Primary repository: ProductDevelopment. repository type: Git
2019-05-25T15:13:21.4330270Z Prepare build directory.
2019-05-25T15:13:21.4594335Z ##[debug]Creating build directory: 'D:\a\1'
2019-05-25T15:13:21.4596963Z ##[debug]Delete existing artifacts directory: 'D:\a\1\a'
2019-05-25T15:13:21.4602844Z ##[debug]Creating artifacts directory: 'D:\a\1\a'
2019-05-25T15:13:21.4604642Z ##[debug]Delete existing test results directory: 'D:\a\1\TestResults'
2019-05-25T15:13:21.4605131Z ##[debug]Creating test results directory: 'D:\a\1\TestResults'
2019-05-25T15:13:21.4606912Z ##[debug]Creating binaries directory: 'D:\a\1\b'
2019-05-25T15:13:21.4612014Z ##[debug]Creating source directory: 'D:\a\1\s'
2019-05-25T15:13:21.4613984Z Set build variables.
2019-05-25T15:13:21.4697732Z Download all required tasks.
2019-05-25T15:13:21.4869070Z Downloading task: ADOScheduledWorkItemQuery
2019-05-25T15:13:22.8194757Z ##[debug]Task 'ADOScheduledWorkItemQuery' has been downloaded into 'D:\a\_tasks\ADOScheduledWorkItemQuery_ed72c92b-b2cb-44d7-b0fa-77691c57a3f1\0.57.0'.
2019-05-25T15:13:22.9517597Z ##[debug]Task 'Checkout' has following condition: 'False'.
2019-05-25T15:13:22.9573265Z ##[debug]Parsing expression: <False>
2019-05-25T15:13:22.9654296Z ##[debug]False
2019-05-25T15:13:22.9713857Z ##[debug]Task 'Send Query Result as E-Mail' has following condition: 'succeeded()'.
2019-05-25T15:13:22.9714552Z ##[debug]Parsing expression: <succeeded()>
2019-05-25T15:13:22.9714745Z ##[debug]succeeded
2019-05-25T15:13:22.9736795Z ##[debug](
2019-05-25T15:13:22.9741980Z ##[debug])
2019-05-25T15:13:23.0040857Z ##[debug]Log plugin 'TestResultLogPlugin' is disabled.
2019-05-25T15:13:23.0041054Z ##[debug]Log plugin 'TestFilePublisherPlugin' is disabled.
2019-05-25T15:13:23.0041930Z Start tracking orphan processes.
2019-05-25T15:13:23.0092975Z ##[section]Finishing: Initialize job
2019-05-25T15:13:23.0271294Z ##[debug]Evaluating condition for step: 'Checkout'
2019-05-25T15:13:23.0384757Z ##[debug]Evaluating: False
2019-05-25T15:13:23.0405717Z ##[debug]Evaluating Boolean:
2019-05-25T15:13:23.0449135Z ##[debug]=> False
2019-05-25T15:13:23.0467143Z ##[debug]Result: False
2019-05-25T15:13:23.0482202Z ##[debug]Evaluating condition for step: 'Send Query Result as E-Mail'
2019-05-25T15:13:23.0495543Z ##[debug]Evaluating: succeeded()
2019-05-25T15:13:23.0495763Z ##[debug]Evaluating succeeded:
2019-05-25T15:13:23.0506610Z ##[debug]=> True
2019-05-25T15:13:23.0523373Z ##[debug]Result: True
2019-05-25T15:13:23.0607520Z ##[section]Starting: Send Query Result as E-Mail
2019-05-25T15:13:23.2663728Z ==============================================================================
2019-05-25T15:13:23.2663995Z Task         : Scheduled Work Item Query
2019-05-25T15:13:23.2664096Z Description  : Sends an E-Mail on a Schedule for Work Item Queries
2019-05-25T15:13:23.2664235Z Version      : 0.57.0
2019-05-25T15:13:23.2664320Z Author       : Quadrotech Solutions AG
2019-05-25T15:13:23.2664467Z Help         : [More Information](https://github.com/Quadrotech/ADOScheduledWorkItemQuery)
2019-05-25T15:13:23.2664631Z ==============================================================================
2019-05-25T15:13:23.6460427Z ##[debug]agent.TempDirectory=D:\a\_temp
2019-05-25T15:13:23.6461099Z ##[debug]loading inputs and endpoints
2019-05-25T15:13:23.6461427Z ##[debug]loading ENDPOINT_AUTH_95bba676-973b-45ef-b5ba-0b742340aadb
2019-05-25T15:13:23.6676034Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_95bba676-973b-45ef-b5ba-0b742340aadb_PASSWORD
2019-05-25T15:13:23.6680539Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_95bba676-973b-45ef-b5ba-0b742340aadb_SMTPFROMEMAILUSERPASSWORD
2019-05-25T15:13:23.6683806Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_95bba676-973b-45ef-b5ba-0b742340aadb_SMTPFROMNAMEUSERPASSWORD
2019-05-25T15:13:23.6691175Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_95bba676-973b-45ef-b5ba-0b742340aadb_SMTPPORTUSERPASSWORD
2019-05-25T15:13:23.6691839Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_95bba676-973b-45ef-b5ba-0b742340aadb_SMTPSERVERUSERPASSWORD
2019-05-25T15:13:23.6692190Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_95bba676-973b-45ef-b5ba-0b742340aadb_TLSOPTIONSUSERPASSWORD
2019-05-25T15:13:23.6692567Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_95bba676-973b-45ef-b5ba-0b742340aadb_USERNAME
2019-05-25T15:13:23.6693801Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2019-05-25T15:13:23.6696211Z ##[debug]loading ENDPOINT_AUTH_SCHEME_95bba676-973b-45ef-b5ba-0b742340aadb
2019-05-25T15:13:23.6697726Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2019-05-25T15:13:23.6699836Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2019-05-25T15:13:23.6702239Z ##[debug]loading INPUT_CONNECTEDSERVICENAMESMTP
2019-05-25T15:13:23.6703963Z ##[debug]loading INPUT_EMAILADDRESSES
2019-05-25T15:13:23.6706002Z ##[debug]loading INPUT_PROJECT
2019-05-25T15:13:23.6707591Z ##[debug]loading INPUT_QUERY
2019-05-25T15:13:23.6709708Z ##[debug]loading INPUT_QUERYTYPE
2019-05-25T15:13:23.6711467Z ##[debug]loading INPUT_SENDIFEMPTY
2019-05-25T15:13:23.6713141Z ##[debug]loading INPUT_SENDMETHOD
2019-05-25T15:13:23.6714838Z ##[debug]loading INPUT_SUBJECT
2019-05-25T15:13:23.6730954Z ##[debug]loaded 20
2019-05-25T15:13:23.6747443Z ##[debug]Agent.ProxyUrl=undefined
2019-05-25T15:13:23.6750047Z ##[debug]Agent.CAInfo=undefined
2019-05-25T15:13:23.6750325Z ##[debug]Agent.ClientCert=undefined
2019-05-25T15:13:23.6750702Z ##[debug]Agent.SkipCertValidation=undefined
2019-05-25T15:13:24.4467948Z ##[debug]project=b9a5c562-3c46-4402-a14a-57cf3dc541d0
2019-05-25T15:13:24.4468189Z ##[debug]sendIfEmpty=true
2019-05-25T15:13:24.4468371Z ##[debug]queryType=Shared
2019-05-25T15:13:24.4469105Z ##[debug]query=70b5e252-272a-4e39-bc73-90b1a96e7c9b
2019-05-25T15:13:24.4469431Z ##[debug]queryType=Shared
2019-05-25T15:13:24.4469612Z ##[debug]SystemVssConnection=https://dev.azure.com/myorg/
2019-05-25T15:13:24.4469781Z ##[debug]emailAddresses=changed-my-email@fake.com
2019-05-25T15:13:24.4469970Z ##[debug]Splitted Addresses: changed-my-email@fake.com
2019-05-25T15:13:24.4470159Z ##[debug]Validating E-Mail address: "changed-my-email@fake.com"
2019-05-25T15:13:24.4470335Z ##[debug]queryType=Shared
2019-05-25T15:13:24.4473983Z ##[debug]SystemVssConnection auth param AccessToken = ***
2019-05-25T15:13:24.4474334Z ##[debug]queryType=Shared
2019-05-25T15:13:24.4474513Z ##[debug]SystemVssConnection=https://dev.azure.com/myorg/
2019-05-25T15:13:24.4474687Z ##[debug]queryType=Shared
2019-05-25T15:13:24.4474864Z ##[debug]query=70b5e252-272a-4e39-bc73-90b1a96e7c9b
2019-05-25T15:13:24.8345658Z ##[debug]{"queryType":2,"queryResultType":2,"asOf":"2019-05-25T15:13:24.670Z","columns":[{"referenceName":"System.Id","name":"ID","url":"https://dev.azure.com/myorg/_apis/wit/fields/System.Id"},{"referenceName":"System.WorkItemType","name":"Work Item Type","url":"https://dev.azure.com/myorg/_apis/wit/fields/System.WorkItemType"},{"referenceName":"System.Title","name":"Title","url":"https://dev.azure.com/myorg/_apis/wit/fields/System.Title"},{"referenceName":"System.AssignedTo","name":"Assigned To","url":"https://dev.azure.com/myorg/_apis/wit/fields/System.AssignedTo"},{"referenceName":"System.State","name":"State","url":"https://dev.azure.com/myorg/_apis/wit/fields/System.State"},{"referenceName":"System.Tags","name":"Tags","url":"https://dev.azure.com/myorg/_apis/wit/fields/System.Tags"},{"referenceName":"Microsoft.VSTS.Common.ClosedDate","name":"Closed Date","url":"https://dev.azure.com/myorg/_apis/wit/fields/Microsoft.VSTS.Common.ClosedDate"}],"sortColumns":[{"field":{"referenceName":"System.Title","name":"Title","url":"https://dev.azure.com/myorg/_apis/wit/fields/System.Title"},"descending":false}],"workItemRelations":[]}
2019-05-25T15:13:24.8474927Z ##[section]Finishing: Send Query Result as E-Mail
2019-05-25T15:13:24.8504285Z ##[debug]Evaluating condition for step: 'Checkout'
2019-05-25T15:13:24.8505333Z ##[debug]Evaluating: AlwaysNode()
2019-05-25T15:13:24.8505526Z ##[debug]Evaluating AlwaysNode:
2019-05-25T15:13:24.8506637Z ##[debug]=> True
2019-05-25T15:13:24.8507093Z ##[debug]Result: True
2019-05-25T15:13:24.8507389Z ##[section]Starting: Checkout
2019-05-25T15:13:24.8615722Z ==============================================================================
2019-05-25T15:13:24.8615829Z Task         : Get sources
2019-05-25T15:13:24.8615913Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
2019-05-25T15:13:24.8616008Z Version      : 1.0.0
2019-05-25T15:13:24.8616075Z Author       : Microsoft
2019-05-25T15:13:24.8616170Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=798199)
2019-05-25T15:13:24.8616258Z ==============================================================================
2019-05-25T15:13:25.3925338Z ##[section]Finishing: Checkout
2019-05-25T15:13:25.3996914Z ##[section]Starting: Finalize Job
2019-05-25T15:13:25.4040062Z Start cleaning up orphan processes.
2019-05-25T15:13:25.4051725Z ##[section]Finishing: Finalize Job
2019-05-25T15:13:25.4113945Z ##[debug]Starting diagnostic file upload.
2019-05-25T15:13:25.4114083Z ##[debug]Setting up diagnostic log folders.
2019-05-25T15:13:25.4116560Z ##[debug]Creating diagnostic log files folder.
2019-05-25T15:13:25.4117612Z ##[debug]Creating diagnostic log environment file.
2019-05-25T15:13:25.7703040Z ##[debug]Creating capabilities file.
2019-05-25T15:13:25.7747629Z ##[debug]Copying 1 worker diag logs.
2019-05-25T15:13:25.7805538Z ##[debug]Copying 1 agent diag logs.
2019-05-25T15:13:25.7809196Z ##[debug]Zipping diagnostic files.
2019-05-25T15:13:25.7848257Z ##[debug]Uploading diagnostic metadata file.
2019-05-25T15:13:25.7895795Z ##[debug]Diagnostic file upload complete.
2019-05-25T15:13:25.7951056Z ##[section]Finishing: Agent job 1
```

**Comment by felipemmasan** [comment] 2019-05-29 13:59
Any news about this issue?

**Comment by vvnaik17** [comment] 2019-05-30 22:41
I am running into the same issue. 

##[section]Starting: Send Query Result as E-Mail
==============================================================================
Task         : Scheduled Work Item Query
Description  : Sends an E-Mail on a Schedule for Work Item Queries
Version      : 0.57.0
Author       : Quadrotech Solutions AG
Help         : [More Information](https://github.com/Quadrotech/ADOScheduledWorkItemQuery)
==============================================================================
##[error]unable to get local issuer certificate
##[error]unable to get local issuer certificate
##[section]Finishing: Send Query Result as E-Mail

**Comment by MichelZ** [comment] 2020-02-14 08:28
Are you by any chance using a query of type "Work Items and Direct Links" (i.e. a hierarchy query) ?

**Comment by philcarbone** [comment] 2020-02-14 19:21
That was it! It works when I change it to a flat list (I didn't even notice it was on 'Tree of work items'

Thank you!

**Comment by MichelZ** [comment] 2020-02-14 20:19
Great! Working on support for this type of query.

Duplicate of #11

**Closed as completed by MichelZ** 2020-02-14 20:19 UTC
Labels: question

**Comment by umairgillani94** [comment] 2021-03-03 09:22
Can anyone help me? I am getting this error when I am running a pipeline :

**Endpoint not present: SystemVssConnection**
